openapi: 3.0.3
info:
  title: Pet API
  description: Pet API
  version: 1.0.0
  contact:
    name: Gleb
    email: glebivashyn@gmail.com
  license:
    name: Open Source
servers:
  - url: 'http://localhost:8099'

paths:
  /pets:
    get:
      summary: Get all pets
      operationId: getAllPets
      description: Get all pets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a pet
      operationId: createPet
      description: Create a pet
      requestBody:
        description: Pet object that needs to be added to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'


#  /pets/{id}:
#    get:
#      summary: Find pet by ID
#      operationId: getPetById
#      parameters:
#        - name: id
#          in: path
#          description: ID of pet to return
#          required: true
#          schema:
#            type: integer
#            format: int64
#      responses:
#        '200':
#          description: OK
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Pet'
#        '400':
#          description: Invalid ID supplied
#        '404':
#          description: Pet not found

components:
  schemas:
    Pet:
      type: object
      description: Pet object
      properties:
        name:
          type: string
        breed:
          type: string
        age:
          type: integer
          format: int32
